export enum FileExtension {

	IMAGE_JPG   = "IMAGE_JPG",
	IMAGE_JPEG  = "IMAGE_JPEG",
	IMAGE_PNG   = "IMAGE_PNG",
	IMAGE_RAW   = "IMAGE_RAW",
	IMAGE_GIF   = "IMAGE_GIF",
	ARCHIVE_ZIP = "ARCHIVE_ZIP",
	ARCHIVE_TAR = "ARCHIVE_TAR",
	ARCHIVE_7Z	= "ARCHIVE_7Z",
	ARCHIVE_RAR = "ARCHIVE_RAR",
	MKV         = "MKV",
	MP3         = "MP3",
	MP4         = "MP4",
	TXT         = "TXT",
	VIM         = "VIM",
	JAR         = "JAR",
	EXE         = "EXE",
	BAT         = "BAT",
	DMG         = "DMG",
	APK         = "APK",
	IMG_EXEC    = "IMG_EXEC",
	SHELL       = "SHELL",
	JAVA        = "JAVA",
	KOTLIN      = "KOTLIN",
	HTML        = "HTML",
	CSS         = "CSS",
	SCSS        = "SCSS",
	JAVASCRIPT  = "JAVASCRIPT",
	TYPESCRIPT  = "TYPESCRIPT",
	JSX         = "JSX",
	TSX         = "TSX",
	GRADLE      = "GRADLE",
	JSON        = "JSON",
	XML         = "XML",
	YML         = "YML",
	OTHER       = "OTHER"
}

