export enum FileExtensionIcons {

	IMAGE_JPG,
	IMAGE_JPEG,
	IMAGE_PNG,
	IMAGE_RAW,
	IMAGE_GIF,
	ARCHIVE_ZIP = "fas fa-file-archive",
	ARCHIVE_TAR = "fas fa-file-archive",
	ARCHIVE_7Z	= "fas fa-file-archive",
	ARCHIVE_RAR = "fas fa-file-archive",
	MKV 		= "fas fa-file-video",
	MP3 		= "fas fa-music",
	MP4 		= "fas fa-music",
	TXT 		= "fas fa-file-alt",
	VIM 		= "fas fa-file-code",
	JAR 		= "icon-java-bold",
	EXE			= "fab fa-windows",
	BAT 		= "fab fa-windows",
	DMG 		= "fab fa-apple",
	APK 		= "fab fa-android",
	IMG_EXEC 	= "fab fa-codepen",
	SHELL 		= "fas fa-terminal",
	JAVA 		= "icon-java-bold",
	KOTLIN 		= "fab fa-kickstarter-k",
	HTML 		= "icon-html5-alt",
	CSS 		= "icon-css3-alt",
	SCSS 		= "icon-css3",
	JAVASCRIPT 	= "icon-javascript-alt",
	TYPESCRIPT 	= "icon-javascript",
	JSX 		= "fab fa-react",
	TSX 		= "fab fa-react",
	GRADLE 		= "icon-gradle",
	JSON 		= "fas fa-code",
	XML 		= "fas fa-code",
	YML 		= "fab fa-y-combinator",
	OTHER 		= "fas fa-file"
}
